### ISSUE TITLE
vc鸡异常

### ISSUE THREAD

**Issue by taosuayou** [pzure/hax-woiden-vc-renew-monitor#5]
cookie正常，但是不能显示到期时间和数据中心
![Screenshot_20240121_132909](https://github.com/pzure/hax-woiden-vc-renew-monitor/assets/102899873/62f2e3b9-26d7-4d98-b11f-4278fec7495a)

**Comment by ZefanHu** [comment]
> cookie正常，但是不能显示到期时间和数据中心 ![Screenshot_20240121_132909](https://private-user-images.githubusercontent.com/102899873/298362268-62f2e3b9-26d7-4d98-b11f-4278fec7495a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNTM5NzUsIm5iZiI6MTcwNjI1MzY3NSwicGF0aCI6Ii8xMDI4OTk4NzMvMjk4MzYyMjY4LTYyZjJlM2I5LTI2ZDctNGQ5OC1iMTFmLTQyNzhmZWM3NDk1YS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNlQwNzIxMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzc5YTY4MTUzMGRiNjE1MmYxMTZiYjI2NTc2NmQzNmY2ODQ5ZjA3ZDk3ZDdhODA0MmRkZDRiN2IyNzJmMzUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.usFICrfwgQrRGPfaDzRwMWVQEW5YG1YMKGh2uIA_ypI)

请问你解决这个问题了吗？我刚刚部署的也是遇到同样的问题。能看一下如何正确配置吗？

**Comment by taosuayou** [comment]
> cookie正常，但是不能显示到期时间和数据中心 ![Screenshot_20240121_132909](https://private-user-images.githubusercontent.com/102899873/298362268-62f2e3b9-26d7-4d98-b11f-4278fec7495a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyODI3MjEsIm5iZiI6MTcwNjI4MjQyMSwicGF0aCI6Ii8xMDI4OTk4NzMvMjk4MzYyMjY4LTYyZjJlM2I5LTI2ZDctNGQ5OC1iMTFmLTQyNzhmZWM3NDk1YS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNlQxNTIwMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTRmYWQyZWNkYmU2YmU1NWJjYjZjMWQyMTI4NzRhN2UwZjMwYWNiOGQ3NzU2N2M2MzcyYjk5MWRkYjhiZDQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PWJdDMLVjS-XRPHfIBeBjXpeZWSXoOUYg1cyvWGhq7c)

解决了，把PHP啥啥啥=的前面一起复制上，粘贴就能用

**Comment by ZefanHu** [comment]
> > cookie正常，但是不能显示到期时间和数据中心 ![Screenshot_20240121_132909](https://private-user-images.githubusercontent.com/102899873/298362268-62f2e3b9-26d7-4d98-b11f-4278fec7495a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyODI3MjEsIm5iZiI6MTcwNjI4MjQyMSwicGF0aCI6Ii8xMDI4OTk4NzMvMjk4MzYyMjY4LTYyZjJlM2I5LTI2ZDctNGQ5OC1iMTFmLTQyNzhmZWM3NDk1YS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNlQxNTIwMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTRmYWQyZWNkYmU2YmU1NWJjYjZjMWQyMTI4NzRhN2UwZjMwYWNiOGQ3NzU2N2M2MzcyYjk5MWRkYjhiZDQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PWJdDMLVjS-XRPHfIBeBjXpeZWSXoOUYg1cyvWGhq7c)
> 
> 解决了，把PHP啥啥啥=的前面一起复制上，粘贴就能用
![image](https://github.com/pzure/hax-woiden-vc-renew-monitor/assets/81904038/d6a86da6-252e-4d00-8795-4adcc64cea6d)
能请你给一个配置的截图吗？我在网页中点击添加监控，网页Cookie设置为PHPSESSID=value000，显示还是不正确。config.ini的cookie你是怎么设置的呢？我config.ini也是填写的PHPSESSID=value000。不知道哪里出错了。请你帮忙看看。
